### ISSUE TITLE
关于路由的格式

### ISSUE THREAD

**Issue by a11266897** [evan2x/node-marmot#1]
是否可以提供多种格式来书写路由。。比如说json 、 xml 、yml格式

**Comment by evan2x** [comment]
`JSON`目前不能写注释，路由中需要注释的地方会比较多一点。至于`YAML`和`XML`，选用`XML`的原因很简单，纯粹是因为JDK本身提供了XML解析器，目前对路由文件的解析是使用StAX的方式。至于`YAML`，需要引入第三方JAR包，并且目前还不会考虑针对多种路由文件格式
